//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLocadora_Interface.ServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.ILocacaoService")]
    public interface ILocacaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocacaoService/selAllLoca", ReplyAction="http://tempuri.org/ILocacaoService/selAllLocaResponse")]
        System.Data.DataTable selAllLoca(string _cli, string _loc, string _vec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocacaoService/selAllLoca", ReplyAction="http://tempuri.org/ILocacaoService/selAllLocaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> selAllLocaAsync(string _cli, string _loc, string _vec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocacaoService/selCliLoc", ReplyAction="http://tempuri.org/ILocacaoService/selCliLocResponse")]
        string selCliLoc(int _codLoc, int _codfun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocacaoService/selCliLoc", ReplyAction="http://tempuri.org/ILocacaoService/selCliLocResponse")]
        System.Threading.Tasks.Task<string> selCliLocAsync(int _codLoc, int _codfun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocacaoService/selPlacaLoc", ReplyAction="http://tempuri.org/ILocacaoService/selPlacaLocResponse")]
        string selPlacaLoc(int _codLoc, int _codfun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocacaoService/selPlacaLoc", ReplyAction="http://tempuri.org/ILocacaoService/selPlacaLocResponse")]
        System.Threading.Tasks.Task<string> selPlacaLocAsync(int _codLoc, int _codfun);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocacaoServiceChannel : WebLocadora_Interface.ServiceReferences.ILocacaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocacaoServiceClient : System.ServiceModel.ClientBase<WebLocadora_Interface.ServiceReferences.ILocacaoService>, WebLocadora_Interface.ServiceReferences.ILocacaoService {
        
        public LocacaoServiceClient() {
        }
        
        public LocacaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocacaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocacaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocacaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable selAllLoca(string _cli, string _loc, string _vec) {
            return base.Channel.selAllLoca(_cli, _loc, _vec);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> selAllLocaAsync(string _cli, string _loc, string _vec) {
            return base.Channel.selAllLocaAsync(_cli, _loc, _vec);
        }
        
        public string selCliLoc(int _codLoc, int _codfun) {
            return base.Channel.selCliLoc(_codLoc, _codfun);
        }
        
        public System.Threading.Tasks.Task<string> selCliLocAsync(int _codLoc, int _codfun) {
            return base.Channel.selCliLocAsync(_codLoc, _codfun);
        }
        
        public string selPlacaLoc(int _codLoc, int _codfun) {
            return base.Channel.selPlacaLoc(_codLoc, _codfun);
        }
        
        public System.Threading.Tasks.Task<string> selPlacaLocAsync(int _codLoc, int _codfun) {
            return base.Channel.selPlacaLocAsync(_codLoc, _codfun);
        }
    }
}
